### ISSUE TITLE
Cannot find module 'gojs'.

### ISSUE THREAD

**Issue by Kyusuph** [NorthwoodsSoftware/gojs-angular-basic#7] opened 2020-07-15 10:35 UTC
How can i get rid of that error am current getting running exactly codes as from from this repo?

It happens on this line "import * as go from 'gojs';" in app.component.ts and inspector.component.ts

**Comment by rjohnson465** [comment] 2020-07-15 18:15
I am unable to reproduce your issue. I just tried downloading the full contents of the repo, installed packages with 'npm i', and ran 'ng serve' with no problems. Did you change any of the files at all?

**Comment by Kyusuph** [comment] 2020-07-16 19:04
I downloaded a zip file from this repo, unzip and ran npm install. After doing so, everything went okay without any issue.
When i ran **_npm install --save gojs-angula_**r and **_npm install gojs_**,  gojs-angular was installed but 'gojs' was not installed hence **_Cannot find module 'gojs'_** error was thrown, any help @rjohnson465

**Comment by rjohnson465** [comment] 2020-07-16 19:23
Why are you installing gojs-angular and gojs individually? They are listed in the package.json for this project, so 'npm install' will be sufficient. Either way, I just tried exactly what you wrote without issue -- I downloaded the repo, ran the install commands you listed, and could serve the angular application just fine. What are you doing differently?

**Comment by rjohnson465** [comment] 2020-07-20 18:56
Closing, feel free to continue commenting if the issue persists

**Closed by rjohnson465** 2020-07-20 18:56 UTC
